version: '3.8'
name: WSearch

services:
  wsearch_main:
    image: postgres:14.5
    container_name: wsearch_main
    restart: always
    environment:
      - POSTGRES_DB=wsearch_main
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin
    ports:
      - 5532:5432
    volumes:
      - pg-data:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.0
    container_name: elasticsearch
    command: >
      bash -c './bin/elasticsearch-plugin list | grep -q analysis-ukrainian || ./bin/elasticsearch-plugin install analysis-icu analysis-ukrainian mapper-murmur3 mapper-size && exec /usr/local/bin/docker-entrypoint.sh'
    environment:
      - xpack.security.enabled=false
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

volumes:
  pg-data:
    driver: local
  es-data:
    driver: local
